### ISSUE TITLE
things about yaw

### ISSUE THREAD

**Issue by CooperBruce** [PBernalPolo/test_MKF#1]
Hi 
   PBernalPolo.Thank you very much for your code,it help me very much.
  I have tried your code, found that the yaw didn't act same as  you show in  video. All your algorithms don't depend on the magnetometer data.
 Is there something i misunderstand?

**Comment by pbernalpolo** [comment]
Hi @CooperBruce ,

I am glad the code helped you. What differences do you find with respect to the videos?

Indeed, the algorithms do not consider magnetometer data to update the state of the KF. The consequence is that the orientation perpendicular to gravity is not absolutely observable (we can only "measure" relative changes with respect to the last orientation using the gyro), which makes the uncertainty in that direction grow unbounded.

I have not found an easy and rigorous way to update the state using magnetometer measurements. Since the magnetic field is different depending on the position on Earth, and it is also dependent on metallic objects in the surroundings of the sensor, I disregarded it as a source of information for orientation. What are your thoughts about this?

**Comment by CooperBruce** [comment]
Hi @PBernalPolo 
Thank you for quick reply.I first saw  the demo video you uploaded on youtube,found that there is no drift  on yaw direction.even after you make  some sudden move,the yaw direction show in video is still good.

Now  i just  do some test about your code without reading it carefully.The differences between my test and the show in video are:
1. when the sensor stay still, the yaw direction changes slowly
2. after some move and turn action,the yaw value is wrong and never recover.

i am wondering  is there some parameters need to tune to fix that two problems.
BTW,i  ,is there a way to predict yaw direction without magnetometer ?

**Comment by pbernalpolo** [comment]
Hi @CooperBruce ,
the behaviors you are describing emerge in my tests as well. It may happen that in my tests they are more subtle because I am using fairly well calibrated IMUs (I assume you are using an uncalibrated IMU - please confirm if this is correct). My calibration considers the scale factors, offsets, and the cross-axis sensitivities, as well as their temperature dependence. However, let me repeat: it happens to me too. The reason is that we lack information to fully determine the orientation. Many people use magnetometers to obtain a "rough" observability of the orientation, but there are indeed other sensors that provide such information. For example, a GPS is an option; check my answer to "Drone District" in:
https://www.youtube.com/watch?v=6oH4Stb2Ifs
Another option could be a camera if you have some external marker whose orientation is known; see the beginning of:
https://www.youtube.com/watch?v=jvfdR7ekSus
The key is to find a sensor that provides measurements related in some way to the orientation and, in particular, to some direction orthogonal to the vertical direction.

**Comment by CooperBruce** [comment]
Thanks a lot for those details.
